ALTER TABLE foods ADD COLUMN view_count BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE foods ADD COLUMN order_count BIGINT DEFAULT 0 NOT NULL;

CREATE TABLE shedlock (
    name VARCHAR(64) NOT NULL,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);
